package com.zhangz.security.mapper;

import com.zhangz.security.model.Kindlist;
import com.zhangz.security.model.KindlistExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface KindlistMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    long countByExample(KindlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int deleteByExample(KindlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int deleteByPrimaryKey(String kindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int insert(Kindlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int insertSelective(Kindlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    List<Kindlist> selectByExampleWithRowbounds(KindlistExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    List<Kindlist> selectByExample(KindlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    Kindlist selectByPrimaryKey(String kindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Kindlist record, @Param("example") KindlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByExample(@Param("record") Kindlist record, @Param("example") KindlistExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByPrimaryKeySelective(Kindlist record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kindlist
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByPrimaryKey(Kindlist record);
}