package com.zhangz.security.mapper;

import com.zhangz.security.model.Site;
import com.zhangz.security.model.SiteExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SiteMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    long countByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int deleteByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int deleteByPrimaryKey(String siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int insert(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int insertSelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    List<Site> selectByExampleWithRowbounds(SiteExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    List<Site> selectByExample(SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    Site selectByPrimaryKey(String siteId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByExampleSelective(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByExample(@Param("record") Site record, @Param("example") SiteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByPrimaryKeySelective(Site record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table site
     *
     * @mbg.generated Sun Apr 19 21:40:06 CST 2020
     */
    int updateByPrimaryKey(Site record);
}