package com.zhangz.security.model;

public class Address {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.parent_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.short_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String shortName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.city_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String cityCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.zip_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String zipCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.merger_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String mergerName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.lng
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String lng;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.lat
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String lat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column address.pinyin
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String pinyin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.id
     *
     * @return the value of address.id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.id
     *
     * @param id the value for address.id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.name
     *
     * @return the value of address.name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.name
     *
     * @param name the value for address.name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.parent_id
     *
     * @return the value of address.parent_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.parent_id
     *
     * @param parentId the value for address.parent_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setParentId(String parentId) {
        this.parentId = parentId == null ? null : parentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.short_name
     *
     * @return the value of address.short_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getShortName() {
        return shortName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.short_name
     *
     * @param shortName the value for address.short_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setShortName(String shortName) {
        this.shortName = shortName == null ? null : shortName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.city_code
     *
     * @return the value of address.city_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.city_code
     *
     * @param cityCode the value for address.city_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode == null ? null : cityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.zip_code
     *
     * @return the value of address.zip_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getZipCode() {
        return zipCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.zip_code
     *
     * @param zipCode the value for address.zip_code
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setZipCode(String zipCode) {
        this.zipCode = zipCode == null ? null : zipCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.merger_name
     *
     * @return the value of address.merger_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getMergerName() {
        return mergerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.merger_name
     *
     * @param mergerName the value for address.merger_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setMergerName(String mergerName) {
        this.mergerName = mergerName == null ? null : mergerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.lng
     *
     * @return the value of address.lng
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getLng() {
        return lng;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.lng
     *
     * @param lng the value for address.lng
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setLng(String lng) {
        this.lng = lng == null ? null : lng.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.lat
     *
     * @return the value of address.lat
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getLat() {
        return lat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.lat
     *
     * @param lat the value for address.lat
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setLat(String lat) {
        this.lat = lat == null ? null : lat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column address.pinyin
     *
     * @return the value of address.pinyin
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getPinyin() {
        return pinyin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column address.pinyin
     *
     * @param pinyin the value for address.pinyin
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setPinyin(String pinyin) {
        this.pinyin = pinyin == null ? null : pinyin.trim();
    }
}