package com.zhangz.security.model;

import java.util.Date;

public class Approval {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approval_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String approvalId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approveded_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String approvededId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approver_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String approverId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approver_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String approverName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approve_date
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private Date approveDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.approve_status
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private Boolean approveStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.type
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column approval.remark
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approval_id
     *
     * @return the value of approval.approval_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getApprovalId() {
        return approvalId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approval_id
     *
     * @param approvalId the value for approval.approval_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApprovalId(String approvalId) {
        this.approvalId = approvalId == null ? null : approvalId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approveded_id
     *
     * @return the value of approval.approveded_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getApprovededId() {
        return approvededId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approveded_id
     *
     * @param approvededId the value for approval.approveded_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApprovededId(String approvededId) {
        this.approvededId = approvededId == null ? null : approvededId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approver_id
     *
     * @return the value of approval.approver_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getApproverId() {
        return approverId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approver_id
     *
     * @param approverId the value for approval.approver_id
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApproverId(String approverId) {
        this.approverId = approverId == null ? null : approverId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approver_name
     *
     * @return the value of approval.approver_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getApproverName() {
        return approverName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approver_name
     *
     * @param approverName the value for approval.approver_name
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApproverName(String approverName) {
        this.approverName = approverName == null ? null : approverName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approve_date
     *
     * @return the value of approval.approve_date
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public Date getApproveDate() {
        return approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approve_date
     *
     * @param approveDate the value for approval.approve_date
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApproveDate(Date approveDate) {
        this.approveDate = approveDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.approve_status
     *
     * @return the value of approval.approve_status
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public Boolean getApproveStatus() {
        return approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.approve_status
     *
     * @param approveStatus the value for approval.approve_status
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setApproveStatus(Boolean approveStatus) {
        this.approveStatus = approveStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.type
     *
     * @return the value of approval.type
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.type
     *
     * @param type the value for approval.type
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column approval.remark
     *
     * @return the value of approval.remark
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column approval.remark
     *
     * @param remark the value for approval.remark
     *
     * @mbg.generated Mon Apr 20 15:51:22 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}