package com.zhangz.security.model;

public class Favorite {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.type
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private String type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.createdate
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private Long createdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.deleted
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private Long deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.creator
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private Long creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column favorite.question_id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    private Long questionId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.id
     *
     * @return the value of favorite.id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.id
     *
     * @param id the value for favorite.id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.type
     *
     * @return the value of favorite.type
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.type
     *
     * @param type the value for favorite.type
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.createdate
     *
     * @return the value of favorite.createdate
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public Long getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.createdate
     *
     * @param createdate the value for favorite.createdate
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setCreatedate(Long createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.deleted
     *
     * @return the value of favorite.deleted
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public Long getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.deleted
     *
     * @param deleted the value for favorite.deleted
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setDeleted(Long deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.creator
     *
     * @return the value of favorite.creator
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public Long getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.creator
     *
     * @param creator the value for favorite.creator
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setCreator(Long creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column favorite.question_id
     *
     * @return the value of favorite.question_id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public Long getQuestionId() {
        return questionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column favorite.question_id
     *
     * @param questionId the value for favorite.question_id
     *
     * @mbg.generated Sun Feb 09 18:28:23 CST 2020
     */
    public void setQuestionId(Long questionId) {
        this.questionId = questionId;
    }
}