package com.zhangz.security.model;

import java.util.Date;

public class SiteCycleExam {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.site_cycle_exam_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String siteCycleExamId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.site_cycle_exam_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String siteCycleExamName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.exam_date
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private Date examDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.exam_status
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String examStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.verifier
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String verifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.verifier_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String verifierName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.site_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String siteId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sitecycleexam.site_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    private String siteName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.site_cycle_exam_id
     *
     * @return the value of sitecycleexam.site_cycle_exam_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getSiteCycleExamId() {
        return siteCycleExamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.site_cycle_exam_id
     *
     * @param siteCycleExamId the value for sitecycleexam.site_cycle_exam_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setSiteCycleExamId(String siteCycleExamId) {
        this.siteCycleExamId = siteCycleExamId == null ? null : siteCycleExamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.site_cycle_exam_name
     *
     * @return the value of sitecycleexam.site_cycle_exam_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getSiteCycleExamName() {
        return siteCycleExamName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.site_cycle_exam_name
     *
     * @param siteCycleExamName the value for sitecycleexam.site_cycle_exam_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setSiteCycleExamName(String siteCycleExamName) {
        this.siteCycleExamName = siteCycleExamName == null ? null : siteCycleExamName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.exam_date
     *
     * @return the value of sitecycleexam.exam_date
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public Date getExamDate() {
        return examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.exam_date
     *
     * @param examDate the value for sitecycleexam.exam_date
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setExamDate(Date examDate) {
        this.examDate = examDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.exam_status
     *
     * @return the value of sitecycleexam.exam_status
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getExamStatus() {
        return examStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.exam_status
     *
     * @param examStatus the value for sitecycleexam.exam_status
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setExamStatus(String examStatus) {
        this.examStatus = examStatus == null ? null : examStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.verifier
     *
     * @return the value of sitecycleexam.verifier
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getVerifier() {
        return verifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.verifier
     *
     * @param verifier the value for sitecycleexam.verifier
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setVerifier(String verifier) {
        this.verifier = verifier == null ? null : verifier.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.verifier_name
     *
     * @return the value of sitecycleexam.verifier_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getVerifierName() {
        return verifierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.verifier_name
     *
     * @param verifierName the value for sitecycleexam.verifier_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setVerifierName(String verifierName) {
        this.verifierName = verifierName == null ? null : verifierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.site_id
     *
     * @return the value of sitecycleexam.site_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getSiteId() {
        return siteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.site_id
     *
     * @param siteId the value for sitecycleexam.site_id
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setSiteId(String siteId) {
        this.siteId = siteId == null ? null : siteId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sitecycleexam.site_name
     *
     * @return the value of sitecycleexam.site_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public String getSiteName() {
        return siteName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sitecycleexam.site_name
     *
     * @param siteName the value for sitecycleexam.site_name
     *
     * @mbg.generated Sat Apr 25 10:03:36 CST 2020
     */
    public void setSiteName(String siteName) {
        this.siteName = siteName == null ? null : siteName.trim();
    }
}